Repository ManageIQ/react-ui-components, pull requests merged in 2018-06, with the labels that each got.

#35 TextualSummary: display nulls as empty strings
  src/textual_summary/data/textual_summary.js
  src/textual_summary/generic_table_row.jsx
  src/textual_summary/stories/TextualSummary.stories.js
  src/textual_summary/tests/__snapshots__/textual_summary.test.js.snap
  src/textual_summary/tests/textual_summary.test.js
Labels: bug

#36 Update packages and use webpack 4
  package.json
  scripts/plugins.js
  scripts/storybook/webpack.config.js
  scripts/webpack.config.js
Labels: unmergeable

#42 Textual improvements
  src/textual_summary/simple_table.jsx
  src/textual_summary/stories/SimpleTable.stories.js
  src/textual_summary/tests/__snapshots__/simple_table.test.js.snap
  src/textual_summary/tests/simple_table.test.js
  src/textual_summary/textual_group.jsx
  src/textual_summary/textual_row.jsx
Labels: enhancement
